version: "3"
services:
  node-app:
    build: 
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=panei
      - MONGO_PASSWORD=mypassword
      - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=panei
      - MONGO_INITDB_ROOT_PASSWORD=mypassword